name: motoHome
display_name: motoHome
version: 1.0.0
theme_key: 2f85b86e3eafed04cdb3df3538f3ed70
author:
  name: Bonpresta
  email: 
  url: https://addons.prestashop.com/en/2_community-developer?contributor=561146
meta:
  compatibility:
    from: 1.7.0.0
    to: ~
  available_layouts:
    layout-full-width:
      name: Full Width
      description: No side columns, ideal for distraction-free pages such as product pages.
    layout-both-columns:
      name: Three Columns
      description: One large central column and 2 side columns.
    layout-left-column:
      name: Two Columns, small left column
      description: Two columns with a small left column
    layout-right-column:
      name: Two Columns, small right column
      description: Two columns with a small right column


global_settings:
  configuration:
    PS_IMAGE_QUALITY: png
  modules:
    to_disable:
      - blockwishlist
      - productcomments
    to_enable:
      - bonask
      - bonbanner
      - bonbannermenu
      - bonbrand
      - boncall
      - boncategoryproduct
      - boncollection
      - boncomments
      - boncompare
      - bonfaq
      - bongdpr
      - bongooglemap
      - bongooglepay
      - boninfinitescroll
      - boninfoban
      - boninstagram
      - bonlookbook
      - bonlookbookfw
      - bonnews
      - bonnewsletter
      - bonnotice
      - bonorder
      - bonportfolio
      - bonpromotion
      - bonreassurance
      - bonsearch
      - bonslider
      - bontab
      - bontheme
      - bonwhatsappchat
      - bonwishlist
      - bonzoom
      - customtab
      - productbutton
      - productcountdown
      - productpurchase
      - productyoutube
      - rolloverimage
      - zendeskchat
  hooks:
    modules_to_hook:
      customerAccount:
        - bonfaq
      displayAdminCustomersForm:
        - ps_emailsubscription
      displayAdminStatsModules:
        - statspersonalinfos
      displayAttributeForm:
        - ps_facetedsearch
      displayAttributeGroupForm:
        - ps_facetedsearch
      displayAttributeGroupPostProcess:
        - ps_facetedsearch
      displayBackOfficeHeader:
        - productcountdown
        - productyoutube
        - bontab
        - bongooglemap
        - customtab
        - bonfaq
        - productpurchase
        - bonwhatsappchat
        - bongooglepay
        - boncollection
        - bonportfolio
        - boninfoban
        - bonbannermenu
        - bonnews
        - boninstagram
        - bonslider
        - bonlookbookfw
        - bonbanner
        - bonpromotion
        - boncategoryproduct
        - bonlookbook
        - bonreassurance
      displayBeforeBodyClosingTag:
        - bonzoom
        - productcountdown
        - productpurchase
        - bonask
        - bongooglepay
        - bonwishlist
        - boncompare
      displaybonCompare:
        - boncompare
      displayBonInstagram:
        - boninstagram
      displayBonreassuranceCustom:
        - bonreassurance
      displayBonSearch:
        - ps_mainmenu
      displayBonWishlist:
        - bonwishlist
      displayButtonScroll:
        - boninfinitescroll
      displayCustomBanner:
        - bongdpr
        - bonnotice
      displayCustomBannerMenu:
        - bonbannermenu
      displayCustomBoncategoryproduct:
        - boncategoryproduct
      displayCustomerAccount:
        - psgdpr
      displayCustonBoncollection:
        - boncollection
      displayCustonBonportfolio:
        - bonportfolio
      displayFeatureForm:
        - ps_facetedsearch
      displayFeaturePostProcess:
        - ps_facetedsearch
      displayFeatureValueForm:
        - ps_facetedsearch
      displayFeatureValuePostProcess:
        - ps_facetedsearch
      displayFooter:
        - ps_contactinfo
        - ps_linklist
        - ps_customeraccountlinks
        - bonorder
        - bonwhatsappchat
        - ps_socialfollow
      displayFooterAfter:
        - blockreassurance
      displayFooterBefore:
        - blockreassurance
        - ps_emailsubscription
      displayFooterProduct:
        - ps_crossselling
      displayGDPRConsent:
        - psgdpr
      displayGoogleMap:
        - bongooglemap
      displayGridButton:
        - bontheme
      displayHome:
        - bonslider
        - bonlookbook
        - bonlookbookfw
        - ps_featuredproducts
        - bonbanner
        - bonbrand
        - bonnews
        - bonpromotion
        - ps_bestsellers
        - productbutton
        - boninstagram
        - boncategoryproduct
      displayLeftColumn:
        - ps_facetedsearch
        - boninfoban
      displayMyAccountBlock:
        - bonfaq
      displayNavFullWidth:
        - blockreassurance
      displayOneClick:
        - bonorder
      displayPaymentReturn:
        - ps_checkpayment
        - ps_wirepayment
      displayProductAdditionalInfo:
        - ps_sharebuttons
        - bonreassurance
      displayProductButton:
        - productbutton
      displayProductButtons:
        - bonbrand
      displayProductCountdownBlock:
        - productcountdown
      displayProductExtraContent:
        - boncomments
      displayProductPopup:
        - bontab
        - bonask
        - boncomments
      displayProductPriceBlock:
        - productcountdown
        - bonbrand
      displayProductPurchaseBlock:
        - productpurchase
      displayProductTab:
        - productyoutube
        - customtab
      displayProductTabContent:
        - productyoutube
        - customtab
      displayPromotion:
        - bonpromotion
      displayReassurance:
        - blockreassurance
      displayRightColumnProduct:
        - boncomments
      displayRolloverImage:
        - rolloverimage
      displaySearch:
        - ps_searchbar
      displayTop:
        - ps_languageselector
        - ps_currencyselector
        - bonsearch
        - bontheme
        - ps_customersignin
        - boncompare
        - bonwishlist
        - ps_shoppingcart
      displayWrapperBottom:
        - bonwhatsappchat
        - bonnewsletter
        - bontheme
        - boncall
      paymentReturn:
        - bongooglepay
      productActions:
        - bongooglepay
  image_types:
    brand:
      width: 300
      height: 195
      scope:
        - manufacturers
        - suppliers
    cart_default:
      width: 167
      height: 167
      scope:
        - products
    category_default:
      width: 900
      height: 222
      scope:
        - categories
    home_default:
      width: 560
      height: 560
      scope:
        - products
    large_default:
      width: 900
      height: 900
      scope:
        - products
        - manufacturers
        - suppliers
    latest_purchase:
      width: 112
      height: 112
      scope:
        - products
    medium_default:
      width: 452
      height: 452
      scope:
        - products
        - manufacturers
        - suppliers
    small_default:
      width: 98
      height: 98
      scope:
        - products
        - categories
        - manufacturers
        - suppliers
    stores_default:
      width: 464
      height: 338
      scope:
        - stores

theme_settings:
  default_layout: layout-full-width
  layouts:
    pagenotfound: layout-full-width
    best-sales: layout-full-width
    contact: layout-full-width
    index: layout-full-width
    manufacturer: layout-full-width
    new-products: layout-full-width
    password: layout-full-width
    prices-drop: layout-full-width
    sitemap: layout-full-width
    supplier: layout-full-width
    address: layout-full-width
    addresses: layout-full-width
    authentication: layout-full-width
    cart: layout-full-width
    discount: layout-full-width
    history: layout-full-width
    identity: layout-full-width
    my-account: layout-full-width
    order-follow: layout-full-width
    order-slip: layout-full-width
    order: layout-full-width
    search: layout-full-width
    stores: layout-full-width
    guest-tracking: layout-full-width
    order-confirmation: layout-full-width
    product: layout-full-width
    category: layout-left-column
    cms: layout-full-width
    module-cheque-payment: layout-full-width
    module-cheque-validation: layout-full-width
    module-bankwire-validation: layout-full-width
    module-bankwire-payment: layout-full-width
    module-cashondelivery-validation: layout-full-width
    module-ps_checkpayment-payment: layout-full-width
    module-ps_checkpayment-validation: layout-full-width
    module-ps_emailsubscription-verification: layout-full-width
    module-ps_emailsubscription-subscription: layout-full-width
    module-ps_shoppingcart-ajax: layout-full-width
    module-ps_wirepayment-payment: layout-full-width
    module-ps_wirepayment-validation: layout-full-width
    module-bonfaq-faq: layout-full-width
    module-bongooglemap-googlemap: layout-full-width

dependencies:
  modules:
    - bonask
    - bonbanner
    - bonbannermenu
    - bonbrand
    - boncall
    - boncategoryproduct
    - boncollection
    - boncomments
    - boncompare
    - bonfaq
    - bongdpr
    - bongooglemap
    - bongooglepay
    - boninfinitescroll
    - boninfoban
    - boninstagram
    - bonlookbook
    - bonlookbookfw
    - bonnews
    - bonnewsletter
    - bonnotice
    - bonorder
    - bonportfolio
    - bonpromotion
    - bonreassurance
    - bonsearch
    - bonslider
    - bontab
    - bontheme
    - bonwhatsappchat
    - bonwishlist
    - bonzoom
    - customtab
    - productbutton
    - productcountdown
    - productpurchase
    - productyoutube
    - rolloverimage
    - zendeskchat
